[package]
name = "pdb_tui"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pdbtbx = "0.11.0"
rgb = "0.8"
nalgebra = "0.32.3"
nalgebra-glm = "0.18.0"
tobj = "4.0.0"
parry3d = "0.13.5"
